services:
  - type: web
    name: mvx-simple-api
    env: node
    plan: starter
    buildCommand: npm ci
    startCommand: node index.js
    nodeVersion: 18.x
    envVars:
      - key: PORT
        value: 3000
      - key: SECURE_TOKEN
        sync: false
      - key: CHAIN
        value: mainnet
      - key: NODE_ENV
        value: production
      - key: API_PROVIDER
        value: https://gateway.multiversx.com
      - key: FIXED_USD_FEE
        value: 0.03
      - key: REWARD_TOKEN
        value: REWARD-cf6eac
      - key: TREASURY_WALLET
        sync: false
    autoDeploy: true
    healthCheckPath: /health
    numInstances: 1 