services:
  - type: web
    name: my-bulido-api
    env: node
    plan: free
    buildCommand: npm ci && node convert-to-js.js
    startCommand: NODE_OPTIONS=--no-warnings node build/index.js
    nodeVersion: 18.19.1
    envVars:
      # Node.js Configuration (force CommonJS)
      - key: NODE_ENV
        value: "production"
      - key: NODE_OPTIONS
        value: "--no-warnings --experimental-modules --experimental-json-modules"
      
      # MultiversX Network Configuration
      - key: API_PROVIDER
        value: "https://api.multiversx.com"
      - key: CHAIN
        value: "mainnet"
      - key: NETWORK
        value: "mainnet"
      
      # Security
      - key: API_KEY
        sync: false
      - key: SECURE_TOKEN
        sync: false
      
      # Token Configuration
      - key: REWARD_TOKEN
        value: "REWARD-cf6eac"
      - key: TREASURY_WALLET
        value: "erd158k2c3aserjmwnyxzpln24xukl2fsvlk9x46xae4dxl5xds79g6sdz37qn"
      
      # API Configuration
      - key: PORT
        value: "8080"
      
      # Rate Limiting
      - key: RATE_LIMIT_WINDOW
        value: "900000" # 15 minutes in milliseconds
      - key: RATE_LIMIT_MAX
        value: "100"    # Maximum 100 requests per window
      
      # Logging
      - key: LOG_LEVEL
        value: "info"
      
    autoDeploy: true
    region: frankfurt
    healthCheckPath: /api/v1/utils/health
    numInstances: 1 