services:
  - type: web
    name: mvx-assets-manager-api
    env: node
    plan: starter
    buildCommand: npm ci && node fix-all-modules.js
    startCommand: node index.js
    nodeVersion: 18.19.1
    envVars:
      - key: PORT
        value: 3000
      - key: API_KEY
        sync: false
      - key: PRIVATE_KEY
        sync: false
      - key: CHAIN
        value: testnet
    autoDeploy: true
    region: frankfurt
    healthCheckPath: /api/v1/utils/health
    numInstances: 1 