services:
  - type: web
    name: my-bulido-api
    env: node
    plan: free
    buildCommand: >
      # Fix dependency versions
      sed -i 's/\^\([0-9]\+\)\.\([0-9]\+\)\.\([0-9]\+\)/\1.\2.\3/g' package.json &&
      # Install dependencies
      npm ci &&
      # Create build directory
      mkdir -p build &&
      # Copy source files to build directory with .js extension
      find src -name "*.ts" | while read file; do
        dir=$(dirname "${file#src/}")
        mkdir -p "build/$dir"
        cp "$file" "build/${file#src/}.js"
        # Replace .ts imports with .js
        sed -i 's/from ..\(.*\)\.ts./from ..\1.js./g' "build/${file#src/}.js"
        sed -i 's/import \(.*\) from \(.*\)\.ts/import \1 from \2.js/g' "build/${file#src/}.js"
        # Remove type annotations
        sed -i 's/: [A-Za-z][A-Za-z0-9_]*//g' "build/${file#src/}.js"
        sed -i 's/: Array<[A-Za-z][A-Za-z0-9_]*>//g' "build/${file#src/}.js"
        # Replace all "extends" and "implements" for simple class declarations
        sed -i 's/extends [A-Za-z][A-Za-z0-9_]*//' "build/${file#src/}.js"
        sed -i 's/implements [A-Za-z][A-Za-z0-9_]*//' "build/${file#src/}.js"
      done &&
      # Copy package.json to build
      cp package.json build/
    startCommand: node build/index.js
    nodeVersion: 18.19.1
    envVars:
      # MultiversX Network Configuration
      - key: API_PROVIDER
        value: "https://api.multiversx.com"
      - key: CHAIN
        value: "mainnet"
      - key: NETWORK
        value: "mainnet"
      
      # Security
      - key: API_KEY
        sync: false
      - key: SECURE_TOKEN
        sync: false
      
      # Token Configuration
      - key: REWARD_TOKEN
        value: "REWARD-cf6eac"
      - key: TREASURY_WALLET
        value: "erd158k2c3aserjmwnyxzpln24xukl2fsvlk9x46xae4dxl5xds79g6sdz37qn"
      
      # API Configuration
      - key: PORT
        value: "8080"
      - key: NODE_ENV
        value: "production"
      
      # Rate Limiting
      - key: RATE_LIMIT_WINDOW
        value: "900000" # 15 minutes in milliseconds
      - key: RATE_LIMIT_MAX
        value: "100"    # Maximum 100 requests per window
      
      # Logging
      - key: LOG_LEVEL
        value: "info"
      
    autoDeploy: true
    region: frankfurt
    healthCheckPath: /api/v1/utils/health
    numInstances: 1 